ingestion:
  INGESTION_LOGGING_LEVEL: INFO
  INGESTION_STORAGE_BACKEND: POSTGRES
  INGESTION_STORAGE_BACKEND_HOST: localhost
  INGESTION_STORAGE_BACKEND_PORT: 5432

scrapers:
  SCRAPER_LOGGING_LEVEL: INFO
  SCRAPER_FILE_OUTPUT_NAME: "scraper_28hse_output.json"
  SCRAPER_INGESTION_SERVICE_HOST: localhost
  SCRAPER_INGESTION_SERVICE_PORT: 8080