# ingestion
INGESTION_LOGGING_LEVEL: INFO
INGESTION_STORAGE_BACKEND: POSTGRES

# storage backends
## postgres
POSTGRES_USER: postgres
POSTGRES_PASSWORD: postgres
INGESTION_DB_HOST: db
INGESTION_DB_PORT: 5432
INGESTION_DB_DBNAME: datascrapingsystem

# scrapers
SCRAPER_LOGGING_LEVEL: INFO
SCRAPER_FILE_OUTPUT_NAME: "scraper_28hse_output.json"
SCRAPER_INGESTION_SERVICE_HOST: localhost
SCRAPER_INGESTION_SERVICE_PORT: 8080